[window]
padding.x = 8
padding.y = 8

[font]
normal.family = "Berkeley Mono"
size = 11

[terminal]
shell = "/usr/sbin/zsh"

[colors.primary]
background = "#050505"
foreground = "#8A8A8A"

[colors.cursor]
text = "#050505"
cursor = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#292929"

[colors.normal]
black = "#151515"
red = "#C38B8B"
green = "#8FA897"
yellow = "#C4B591"
blue = "#8094B8"
magenta = "#A787A5"
cyan = "#7AA2A6"
white = "#B8B8B8"

[colors.bright]
black = "#4A4A4A"
red = "#D49999"
green = "#A4BBAD"
yellow = "#D8C9A3"
blue = "#91A8CC"
magenta = "#B898B8"
cyan = "#8DB8BC"
white = "#D0D0D0"
